### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by BitByBitByBitByBit** [BTCMedia/B24-Open-Source-Program#234]
I am a passionate bitcoiner from Colombia and I would love to attend for the first time the Bitcoin Conference! 

I am part of the Bitcoin Core translation team currently working on the Colombian Spanish localization. Please find below the confirmation in the comments.

I have also contributed as a translator to the Damus app in Latin American Spanish. Terry Yiu from the Damus developer team can vouch for me. Please see his nostr note here (part of a conversation with Matt O'Dell):
 note146hgj7568y9cda6rk2wdlxajsvwng2793lf7mrjlem099gcq73zq6g8g5t

https://brb.io/n/aeae897a9a390b86f743b29cdf9bb2831d342bc58fd3ed8e5fcede52a300f444

Thanks!

**Comment by bitcointranslations** [comment]
To whom it may concern,

I hereby confirm that BitByBit is a member of the Bitcoin.org translation team who is actively contributing to our Spanish translation/localization efforts.

George Glosson
Bitcoin.org Translation Team Coordinator
